services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crazy-task-tracker
    ports:
      - "5433:5432" # Внешний порт:Внутренний порт
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: